Repository woowacourse-teams/2020-zeze, pull requests merged in 2020-08, with the labels that each got.

#94 Feat/#65 user authorization
  src/main/java/dev/minguinho/zeze/config/WebConfig.java
  src/main/java/dev/minguinho/zeze/domain/auth/api/dto/response/UserResourceResponse.java
  src/main/java/dev/minguinho/zeze/domain/auth/config/AuthorizationInterceptor.java
  src/main/java/dev/minguinho/zeze/domain/auth/config/Secured.java
  src/main/java/dev/minguinho/zeze/domain/auth/infra/AuthorizationTokenExtractor.java
  src/main/java/dev/minguinho/zeze/domain/auth/infra/JwtTokenProvider.java
  src/main/java/dev/minguinho/zeze/domain/auth/model/Authority.java
  src/main/java/dev/minguinho/zeze/domain/auth/model/User.java
  src/main/java/dev/minguinho/zeze/domain/auth/service/TokenService.java
  src/main/java/dev/minguinho/zeze/domain/common/model/BaseEntity.java
  src/main/java/dev/minguinho/zeze/domain/slide/api/SlideController.java
  src/main/java/dev/minguinho/zeze/domain/user/api/LoginUserController.java
  src/main/java/dev/minguinho/zeze/domain/user/api/dto/UserResourceRequestDto.java
  src/main/java/dev/minguinho/zeze/domain/user/api/dto/UserResourceResponseDto.java
  src/main/java/dev/minguinho/zeze/domain/user/config/LoginUserId.java
  src/main/java/dev/minguinho/zeze/domain/user/config/LoginUserIdMethodArgumentResolver.java
  src/main/java/dev/minguinho/zeze/domain/user/config/LoginUserInterceptor.java
  src/main/java/dev/minguinho/zeze/domain/user/model/UserResource.java
  src/main/java/dev/minguinho/zeze/domain/user/service/UserResourceService.java
  src/test/java/dev/minguinho/zeze/domain/auth/api/dto/response/UserResourceResponseTest.java
  src/test/java/dev/minguinho/zeze/domain/auth/infra/JwtTokenProviderTest.java
  src/test/java/dev/minguinho/zeze/domain/auth/service/AuthServiceTest.java
  src/test/java/dev/minguinho/zeze/domain/auth/service/TokenServiceTest.java
  src/test/java/dev/minguinho/zeze/domain/file/api/FileControllerTest.java
  src/test/java/dev/minguinho/zeze/domain/slide/api/SlideControllerTest.java
Labels: feat

#96 refactor: use restassured
  build.gradle
  src/main/java/dev/minguinho/zeze/domain/slide/model/Slide.java
  src/main/java/dev/minguinho/zeze/domain/slide/service/SlideService.java
  src/test/java/dev/minguinho/zeze/domain/slide/acceptance/SlideAcceptanceTest.java
  src/test/java/dev/minguinho/zeze/domain/slide/model/SlideRepositoryTest.java
  src/test/java/dev/minguinho/zeze/domain/slide/service/SlideServiceTest.java
Labels: refactor

#98 Refactor/#97 client side refactoring
  client/src/App.tsx
  client/src/api/index.ts
  client/src/api/slide.ts
  client/src/assets/icons/archive.svg
  client/src/assets/icons/index.ts
  client/src/assets/icons/logo.svg
  client/src/assets/icons/menu.svg
  client/src/assets/icons/more.svg
  client/src/assets/icons/newSlides.svg
  client/src/assets/icons/play.svg
  client/src/assets/icons/recent.svg
  client/src/assets/icons/slide.svg
  client/src/assets/icons/user.svg
  client/src/components/common/Card.tsx
  client/src/components/common/Cards.tsx
  client/src/components/common/Footer.tsx
  client/src/components/common/FullScreenMode.tsx
  client/src/components/common/GlobalLayout.tsx
  client/src/components/common/Header.tsx
  client/src/components/common/SidebarHeader.tsx
  client/src/components/common/SidebarLayout.tsx
  client/src/components/common/SidebarMenu.tsx
  client/src/components/common/Spinner.tsx
  client/src/components/common/Toast.tsx
  client/src/components/common/assets/index.ts
  client/src/components/common/markdown/renderers/Code.tsx
  client/src/components/editor/EditMode.tsx
  client/src/components/editor/MarkdownEditor.tsx
  client/src/components/editor/Preview.tsx
  client/src/components/editor/assets/index.ts
  client/src/components/editor/index.tsx
  client/src/components/home/assets/index.ts
  client/src/components/home/assets/markdown.png
  client/src/components/home/index.tsx
  client/src/components/markdown/extensions/Metadata.tsx
  client/src/components/markdown/extensions/Youtube.tsx
  client/src/components/markdown/extensions/index.ts
  client/src/components/markdown/index.tsx
  client/src/components/markdown/renderers/Code.tsx
  client/src/components/markdown/renderers/Image.tsx
  client/src/components/markdown/renderers/index.ts
  client/src/components/theme/index.ts
  client/src/domains/constants.ts
  client/src/domains/types.ts
  client/src/hooks/index.ts
  client/src/index.css
  client/src/index.tsx
  client/src/pages/Archive.tsx
  client/src/pages/Editor.tsx
  client/src/pages/Error.tsx
  client/src/pages/Home.tsx
  client/src/pages/Me.tsx
  client/src/utils/fixtures.ts
  client/src/utils/index.ts
  client/src/utils/metadata.ts
Labels: refactor

#99 Feat/#77 Slides API Integration
  client/package.json
  client/src/App.tsx
  client/src/api/file.ts
  client/src/api/index.ts
  client/src/api/slide.ts
  client/src/components/common/Cards.tsx
  client/src/components/editor/MarkdownEditor.tsx
  client/src/pages/Archive.tsx
  client/src/pages/Editor.tsx
  client/src/pages/Me.tsx
Labels: feat

#102 Style/#9 add GitHub md theme
  client/src/components/common/FullScreenMode.tsx
  client/src/components/editor/Preview.tsx
  client/src/components/markdown/extensions/Metadata.tsx
  client/src/components/markdown/extensions/index.ts
  client/src/components/markdown/index.tsx
  client/src/components/markdown/renderers/Image.tsx
  client/src/components/markdown/renderers/Paragraph.tsx
  client/src/components/markdown/renderers/index.ts
  client/src/components/theme/github.ts
  client/src/components/theme/index.ts
  client/src/pages/Editor.tsx
  client/src/utils/fixtures.ts
  client/src/utils/metadata.ts
  client/yarn.lock
Labels: style

#106 feat: add sql import for user authority
  src/main/resources/import.sql
Labels: feat

#103 feat: apply user to slide
  src/main/java/dev/minguinho/zeze/domain/slide/api/SlideController.java
  src/main/java/dev/minguinho/zeze/domain/slide/api/dto/SlideRequestDto.java
  src/main/java/dev/minguinho/zeze/domain/slide/exception/SlideNotAuthorizedException.java
  src/main/java/dev/minguinho/zeze/domain/slide/model/Slide.java
  src/main/java/dev/minguinho/zeze/domain/slide/model/SlideRepository.java
  src/main/java/dev/minguinho/zeze/domain/slide/service/SlideService.java
  src/main/java/dev/minguinho/zeze/exception/ExceptionController.java
  src/test/java/dev/minguinho/zeze/domain/slide/acceptance/SlideAcceptanceTest.java
  src/test/java/dev/minguinho/zeze/domain/slide/api/SlideControllerTest.java
  src/test/java/dev/minguinho/zeze/domain/slide/model/SlideRepositoryTest.java
  src/test/java/dev/minguinho/zeze/domain/slide/service/SlideServiceTest.java
Labels: feat

#107 Refactor/#100 client state management
  client/package.json
  client/src/api/slide.ts
  client/src/components/common/Cards.tsx
  client/src/components/common/FullScreenMode.tsx
  client/src/components/common/SidebarLayout.tsx
  client/src/components/common/SidebarNav.tsx
  client/src/components/markdown/index.tsx
  client/src/components/theme/github.ts
  client/src/domains/constants.ts
  client/src/index.tsx
  client/src/pages/Archive.tsx
  client/src/pages/Editor.tsx
  client/src/pages/Me.tsx
  client/src/store/atoms.ts
  client/src/utils/metadata.ts
Labels: refactor

#109 Feat/#55 login
  client/src/App.tsx
  client/src/api/file.ts
  client/src/api/slide.ts
  client/src/domains/constants.ts
  client/src/pages/Callback.tsx
  client/src/pages/Home.tsx
Labels: feat

#115 Refactor/#112 optimize rendering
  client/src/App.tsx
  client/src/components/editor/MarkdownEditor.tsx
  client/src/components/markdown/index.tsx
  client/src/components/markdown/renderers/Code.tsx
  client/src/components/markdown/renderers/Image.tsx
  client/src/index.tsx
  client/src/pages/Editor.tsx
Labels: fix, refactor

#114 infra: modify deploy.yml and create clientBuild.yml
  .github/workflows/deployBack.yml
  .github/workflows/deployFront.yml
Labels: infra

#119 Feat/#12 embed chart
  client/package.json
  client/src/components/markdown/extensions/Chart.tsx
  client/src/components/markdown/extensions/index.ts
  client/src/components/markdown/index.tsx
  client/src/components/markdown/renderers/Code.tsx
  client/src/utils/fixtures.ts
  client/yarn.lock
Labels: feat

#121 feat: combine methods
  src/main/java/dev/minguinho/zeze/domain/slide/api/SlideController.java
  src/main/java/dev/minguinho/zeze/domain/slide/service/SlideService.java
  src/test/java/dev/minguinho/zeze/domain/slide/acceptance/SlideAcceptanceTest.java
  src/test/java/dev/minguinho/zeze/domain/slide/api/SlideControllerTest.java
  src/test/java/dev/minguinho/zeze/domain/slide/service/SlideServiceTest.java
Labels: feat

#117 Docs/#108 documentation
  build.gradle
  client/package-lock.json
  client/src/api/slide.ts
  client/src/store/atoms.ts
  src/docs/asciidoc/index.adoc
  src/main/java/dev/minguinho/zeze/domain/slide/api/dto/SlideResponseDtos.java
  src/main/java/dev/minguinho/zeze/domain/user/api/LoginUserController.java
  src/main/java/dev/minguinho/zeze/domain/user/config/LoginUserInterceptor.java
  src/main/java/dev/minguinho/zeze/pagecontroller/PageController.java
  src/main/resources/templates/index.html
  src/test/java/dev/minguinho/zeze/domain/documentation/Documentation.java
  src/test/java/dev/minguinho/zeze/domain/documentation/DocumentationConfig.java
  src/test/java/dev/minguinho/zeze/domain/documentation/TestAuthorizationInterceptor.java
  src/test/java/dev/minguinho/zeze/domain/documentation/TestLoginUserInterceptor.java
  src/test/java/dev/minguinho/zeze/domain/file/api/FileControllerTest.java
  src/test/java/dev/minguinho/zeze/domain/file/documentation/FileDocumentation.java
  src/test/java/dev/minguinho/zeze/domain/slide/acceptance/SlideAcceptanceTest.java
  src/test/java/dev/minguinho/zeze/domain/slide/api/SlideControllerTest.java
  src/test/java/dev/minguinho/zeze/domain/slide/documentation/SlideDocumentation.java
  src/test/java/dev/minguinho/zeze/domain/slide/service/SlideServiceTest.java
  src/test/java/dev/minguinho/zeze/domain/user/documentation/UserDocumentation.java
Labels: docs

#122 CI/#34 Deploy Automation (main branch)
  .github/workflows/build.yml
  .github/workflows/deployBack.yml
  .github/workflows/deployFront.yml
Labels: ci

#118 Feat/#77 user api
  client/src/api/user.ts
  client/src/components/common/Card.tsx
  client/src/components/common/Cards.tsx
  client/src/components/common/Info.tsx
  client/src/components/common/SidebarLayout.tsx
  client/src/components/common/SidebarNav.tsx
  client/src/pages/Archive.tsx
  client/src/pages/Callback.tsx
  client/src/pages/Editor.tsx
  client/src/pages/Me.tsx
  client/src/store/atoms.ts
  src/main/java/dev/minguinho/zeze/domain/user/config/LoginUserIdMethodArgumentResolver.java
Labels: feat

#127 Feat/#126 remove youtube size properties
  client/src/components/markdown/extensions/Youtube.tsx
  client/src/utils/fixtures.ts
Labels: feat

#124 Fix/#123 mixed content
  client/public/index.html
Labels: fix

#129 Feat/#128 set client environment variable
  .gitignore
  client/.env.development
  client/.env.production
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/api/file.ts
  client/src/api/slide.ts
  client/src/api/user.ts
  client/src/domains/constants.ts
  client/src/pages/Callback.tsx
  client/yarn.lock
Labels: feat

#135 Feat/#133 style editor button
  client/src/assets/icons/clear.svg
  client/src/assets/icons/index.ts
  client/src/assets/icons/save.svg
  client/src/components/common/FullScreenMode.tsx
  client/src/pages/Editor.tsx
Labels: style

#140 Fix/#138 markdown table
  client/src/components/common/FullScreenMode.tsx
  client/src/components/markdown/index.tsx
  client/src/store/atoms.ts
  client/src/utils/metadata.ts
Labels: fix

#146 Feat/#144 off auto complete
  client/src/components/common/Info.tsx
Labels: feat

#145 Feat/#142 delete warn toast
  client/src/pages/Archive.tsx
  client/src/pages/Me.tsx
Labels: feat

#155 Feat/#116 develop user permission per page
  client/src/App.tsx
  client/src/api/slide.ts
  client/src/api/user.ts
  client/src/assets/icons/index.ts
  client/src/components/common/Card.tsx
  client/src/components/common/Cards.tsx
  client/src/components/common/Info.tsx
  client/src/components/common/SidebarLayout.tsx
  client/src/pages/Auth.tsx
  client/src/pages/Callback.tsx
  client/src/pages/Editor.tsx
  client/src/pages/Me.tsx
  client/src/store/atoms.ts
Labels: feat

#149 feat: add key events
  client/src/App.tsx
  client/src/assets/icons/clear.svg
  client/src/assets/icons/save.svg
  client/src/components/common/FullScreenMode.tsx
  client/src/components/common/Info.tsx
  client/src/components/editor/MarkdownEditor.tsx
  client/src/components/markdown/extensions/Chart.tsx
  client/src/components/markdown/extensions/Youtube.tsx
  client/src/components/markdown/index.tsx
  client/src/components/markdown/renderers/Code.tsx
  client/src/components/markdown/renderers/Image.tsx
  client/src/components/theme/index.ts
  client/src/index.tsx
  client/src/pages/Editor.tsx
  client/src/pages/Me.tsx
  client/src/store/atoms.ts
  client/src/utils/metadata.ts
Labels: feat

#162 Feat/#147/change datetime format
  client/package-lock.json
  client/package.json
  client/src/components/common/Card.tsx
  client/yarn.lock
Labels: feat

#168 Fix/#54 fullscreen youtube
  client/src/components/common/FullScreenMode.tsx
  client/src/components/markdown/extensions/Youtube.tsx
Labels: fix

#167 Chore/#166 google analytics
  client/package.json
  client/src/App.tsx
  client/src/pages/Archive.tsx
  client/src/pages/Callback.tsx
  client/src/pages/Editor.tsx
  client/src/pages/Error.tsx
  client/src/pages/Home.tsx
  client/src/pages/Me.tsx
  client/src/store/atoms.ts
  client/src/utils/googleAnalytics.ts
  client/yarn.lock
Labels: chore

#173 Feat/#172 include metadata
  client/src/components/markdown/index.tsx
  client/src/pages/Editor.tsx
  client/src/utils/metadata.ts
Labels: feat

#175 Feat/#174 chart axis options
  client/src/components/markdown/extensions/Chart.tsx
Labels: feat

#180 Feat/#177 show carousel slide
  client/src/assets/icons/left-arrow.svg
  client/src/assets/icons/right-arrow.svg
  client/src/components/common/Carousel.tsx
  client/src/components/common/FullScreenMode.tsx
  client/src/components/common/SlideExample.tsx
  client/src/pages/Home.tsx
Labels: feat

#179 Fix/#161 change alert to toast message
  client/src/App.tsx
  client/src/assets/icons/index.ts
  client/src/assets/icons/toast_check.svg
  client/src/assets/icons/toast_error.svg
  client/src/assets/icons/toast_info.svg
  client/src/assets/icons/toast_warn.svg
  client/src/components/common/ToastAlarm.tsx
  client/src/domains/ToastFactory.ts
  client/src/domains/constants.ts
  client/src/index.tsx
  client/src/pages/Editor.tsx
  client/src/pages/Me.tsx
  client/src/store/atoms.ts
Labels: fix

#165 Feat/#66 upload external image files using drag and drop
  client/src/api/file.ts
  client/src/components/editor/MarkdownEditor.tsx
  client/src/pages/Editor.tsx
  src/docs/asciidoc/index.adoc
  src/main/java/dev/minguinho/zeze/domain/file/api/FileController.java
  src/main/java/dev/minguinho/zeze/domain/file/api/dto/FileUploadRequestDto.java
  src/main/java/dev/minguinho/zeze/domain/file/api/dto/FileUrlResponsesDto.java
  src/main/java/dev/minguinho/zeze/domain/file/model/S3Uploader.java
  src/main/java/dev/minguinho/zeze/domain/file/service/FileService.java
  src/test/java/dev/minguinho/zeze/domain/file/api/FileControllerTest.java
  src/test/java/dev/minguinho/zeze/domain/file/documentation/FileDocumentation.java
  src/test/java/dev/minguinho/zeze/domain/file/model/S3UploaderTest.java
  src/test/java/dev/minguinho/zeze/domain/file/service/FileServiceTest.java
Labels: feat

#185 hotfix: editor rerendering issue
  client/src/components/common/ToastAlarm.tsx
  client/src/pages/Editor.tsx
Labels: feat, fix

#181 Feat/#169 show the number of pages
  client/src/api/slide.ts
  client/src/components/common/Cards.tsx
  client/src/components/common/Pagination.tsx
  client/src/components/common/SidebarLayout.tsx
  client/src/components/common/SlidesLayout.tsx
  client/src/domains/constants.ts
  client/src/pages/Archive.tsx
  client/src/pages/Editor.tsx
  client/src/pages/Me.tsx
  client/src/store/atoms.ts
  src/main/java/dev/minguinho/zeze/domain/slide/api/dto/SlideResponseDtos.java
  src/main/java/dev/minguinho/zeze/domain/slide/api/dto/SlidesRequestDto.java
  src/main/java/dev/minguinho/zeze/domain/slide/model/SlideRepository.java
  src/main/java/dev/minguinho/zeze/domain/slide/service/SlideService.java
  src/test/java/dev/minguinho/zeze/domain/slide/acceptance/SlideAcceptanceTest.java
  src/test/java/dev/minguinho/zeze/domain/slide/api/SlideControllerTest.java
  src/test/java/dev/minguinho/zeze/domain/slide/documentation/SlideDocumentation.java
  src/test/java/dev/minguinho/zeze/domain/slide/model/SlideRepositoryTest.java
  src/test/java/dev/minguinho/zeze/domain/slide/service/SlideServiceTest.java
Labels: feat

#186 Refactor/#178 move src/assets to public/assets
  client/public/assets/icons/archive.svg
  client/public/assets/icons/clear.svg
  client/public/assets/icons/left-arrow.svg
  client/public/assets/icons/logo.svg
  client/public/assets/icons/menu.svg
  client/public/assets/icons/more.svg
  client/public/assets/icons/newSlides.svg
  client/public/assets/icons/play.svg
  client/public/assets/icons/recent.svg
  client/public/assets/icons/right-arrow.svg
  client/public/assets/icons/save.svg
  client/public/assets/icons/slide.svg
  client/public/assets/icons/toast_check.svg
  client/public/assets/icons/toast_error.svg
  client/public/assets/icons/toast_info.svg
  client/public/assets/icons/toast_warn.svg
  client/public/assets/icons/user.svg
  client/src/assets/icons/index.ts
  client/src/components/common/Carousel.tsx
  client/src/components/common/FullScreenMode.tsx
  client/src/components/common/Header.tsx
  client/src/components/common/SidebarHeader.tsx
  client/src/components/common/SidebarNav.tsx
  client/src/domains/ToastFactory.ts
  client/src/pages/Editor.tsx
  client/src/pages/Error.tsx
  client/src/pages/Home.tsx
Labels: chore, refactor

#170 Feat/#151 private public
  client/public/assets/icons/private.svg
  client/public/assets/icons/public.svg
  client/src/App.tsx
  client/src/api/slide.ts
  client/src/components/common/Info.tsx
  client/src/components/common/Pagination.tsx
  client/src/components/common/SlidesLayout.tsx
  client/src/pages/Archive.tsx
  client/src/pages/Editor.tsx
  client/src/pages/Me.tsx
  client/src/store/atoms.ts
  src/main/java/dev/minguinho/zeze/domain/user/config/LoginUserIdMethodArgumentResolver.java
Labels: feat

#183 Feat/#176 editor menu
  client/src/assets/icons/editor/bullets.svg
  client/src/assets/icons/editor/chart.svg
  client/src/assets/icons/editor/code.svg
  client/src/assets/icons/editor/heading.svg
  client/src/assets/icons/editor/image.svg
  client/src/assets/icons/editor/link.svg
  client/src/assets/icons/editor/list.svg
  client/src/assets/icons/editor/page.svg
  client/src/assets/icons/editor/quote.svg
  client/src/assets/icons/editor/table.svg
  client/src/assets/icons/editor/youtube.svg
  client/src/assets/icons/hamburger.svg
  client/src/components/common/EditorButton.tsx
  client/src/components/common/EditorButtons.tsx
  client/src/components/common/FullScreenMode.tsx
  client/src/components/common/LastModified.tsx
  client/src/components/common/SidebarLayout.tsx
  client/src/components/common/SidebarNav.tsx
  client/src/components/editor/MarkdownEditor.tsx
  client/src/domains/templates.ts
  client/src/pages/Archive.tsx
  client/src/pages/Editor.tsx
  client/src/pages/Me.tsx
  client/src/store/atoms.ts
Labels: feat, style

#193 Feat/#191 modified time
  client/src/components/common/EditorButtons.tsx
  client/src/components/common/LastModified.tsx
  client/src/pages/Editor.tsx
Labels: feat

#201 fix: get public slide of other user
  src/main/java/dev/minguinho/zeze/domain/slide/service/SlideService.java
Labels: fix

#203 feat: modify editor page
  client/src/api/slide.ts
  client/src/pages/Editor.tsx
  src/main/java/dev/minguinho/zeze/domain/slide/api/SlideController.java
  src/main/java/dev/minguinho/zeze/domain/slide/service/SlideService.java
Labels: feat

#200 chore: update issue templates
  .github/ISSUE_TEMPLATE/-----------.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: chore

#204 Fix/#197 v1 final - kimhodol
  client/src/assets/icons/plus.svg
  client/src/assets/icons/remote/back.svg
  client/src/assets/icons/remote/exit.svg
  client/src/assets/icons/remote/next.svg
  client/src/assets/logo192.png
  client/src/components/common/EditorButtons.tsx
  client/src/components/common/FullScreenMode.tsx
  client/src/components/common/Header.tsx
  client/src/components/common/MobileHeader.tsx
  client/src/components/common/MobileSlidesButtons.tsx
  client/src/components/common/SidebarHeader.tsx
  client/src/components/common/SidebarLayout.tsx
  client/src/components/common/SidebarNav.tsx
  client/src/components/common/SlideExample.tsx
  client/src/components/common/Toast.tsx
  client/src/components/common/ToastAlarm.tsx
  client/src/components/editor/MarkdownEditor.tsx
  client/src/components/editor/Preview.tsx
  client/src/components/markdown/index.tsx
  client/src/components/markdown/renderers/Link.tsx
  client/src/components/markdown/renderers/index.ts
  client/src/domains/constants.ts
  client/src/pages/Callback.tsx
  client/src/pages/Editor.tsx
  client/src/pages/Error.tsx
  client/src/pages/Home.tsx
  client/src/pages/Me.tsx
  client/src/pages/PublicSlides.tsx
Labels: fix, high priority

#206 Feat/#195 delete slide
  client/src/components/common/Card.tsx
  client/src/components/common/Cards.tsx
  client/src/components/common/ConfirmModal.tsx
  client/src/components/common/Modal.tsx
  client/src/components/common/SlidesLayout.tsx
  client/src/pages/Me.tsx
  src/main/java/dev/minguinho/zeze/domain/slide/api/SlideController.java
  src/main/java/dev/minguinho/zeze/domain/slide/model/Slide.java
  src/main/java/dev/minguinho/zeze/domain/slide/model/SlideRepository.java
  src/main/java/dev/minguinho/zeze/domain/slide/service/SlideService.java
  src/main/resources/db/migration/V6__Alter_Table_Slide.sql
  src/test/java/dev/minguinho/zeze/domain/slide/api/SlideControllerTest.java
  src/test/java/dev/minguinho/zeze/domain/slide/model/SlideRepositoryTest.java
  src/test/java/dev/minguinho/zeze/domain/slide/model/SlideTest.java
  src/test/java/dev/minguinho/zeze/domain/slide/service/SlideServiceTest.java
Labels: feat

#207 Fix/#205 invalid token
  client/src/store/atoms.ts
  src/main/java/dev/minguinho/zeze/domain/auth/config/AuthorizationInterceptor.java
  src/main/java/dev/minguinho/zeze/domain/auth/config/Secured.java
  src/main/java/dev/minguinho/zeze/domain/auth/infra/JwtTokenProvider.java
  src/main/java/dev/minguinho/zeze/domain/user/api/LoginUserController.java
  src/main/java/dev/minguinho/zeze/exception/ExceptionController.java
  src/test/java/dev/minguinho/zeze/domain/auth/infra/JwtTokenProviderTest.java
  src/test/java/dev/minguinho/zeze/domain/user/documentation/UserDocumentation.java
Labels: fix

#211 Feat/#196 clone slide
  client/src/api/slide.ts
  client/src/components/common/Card.tsx
  client/src/components/common/Modal.tsx
  client/src/components/common/SlidesLayout.tsx
  client/src/pages/Me.tsx
  client/src/pages/PublicSlides.tsx
  src/docs/asciidoc/index.adoc
  src/main/java/dev/minguinho/zeze/domain/slide/api/SlideController.java
  src/main/java/dev/minguinho/zeze/domain/slide/model/Slide.java
  src/main/java/dev/minguinho/zeze/domain/slide/service/SlideService.java
  src/test/java/dev/minguinho/zeze/domain/slide/acceptance/SlideAcceptanceTest.java
  src/test/java/dev/minguinho/zeze/domain/slide/api/SlideControllerTest.java
  src/test/java/dev/minguinho/zeze/domain/slide/documentation/SlideDocumentation.java
  src/test/java/dev/minguinho/zeze/domain/slide/service/SlideServiceTest.java
Labels: feat

#210 Feat/#208 empty slide list
  client/src/components/common/Cards.tsx
  client/src/components/common/SlidesLayout.tsx
Labels: feat

#214 fix/#209 access level message
  client/src/components/common/SlidesLayout.tsx
  client/src/pages/Callback.tsx
  client/src/pages/Editor.tsx
  client/src/pages/Me.tsx
Labels: feat, fix

#215 Fix/ image renderer
  client/src/components/common/FullScreenMode.tsx
  client/src/components/editor/Preview.tsx
  client/src/components/markdown/renderers/Image.tsx
Labels: fix

#218 hotfix/change card title length
  client/src/components/common/Card.tsx
Labels: feat, fix

#224 Fix/#223 invalid html rendering bug
  client/src/components/common/FullScreenMode.tsx
  client/src/components/markdown/index.tsx
  client/src/utils/metadata.ts
Labels: fix, 🐞 bug report

#222 fix: change profile font size
  client/src/components/common/Info.tsx
Labels: fix

#226 fix: order public slides
  src/main/java/dev/minguinho/zeze/domain/slide/model/SlideRepository.java
  src/main/java/dev/minguinho/zeze/domain/slide/service/SlideService.java
  src/test/java/dev/minguinho/zeze/domain/slide/service/SlideServiceTest.java
Labels: fix

#227 Fix/#225 mobile fullscreen bug
  client/src/components/common/FullScreenMode.tsx
Labels: fix, 🐞 bug report

#228 Fix/#225 mobile fullscreen with react device detect
  client/package.json
  client/src/components/common/FullScreenMode.tsx
  client/yarn.lock
Labels: fix

#236 Fix/#235 history back after login
  client/src/pages/Callback.tsx
Labels: fix, 🐞 bug report

#238 fix: list indent
  client/src/domains/templates.ts
Labels: fix

#237 Fix/#231 fix css
  client/src/components/common/Cards.tsx
  client/src/components/common/Carousel.tsx
  client/src/pages/Home.tsx
Labels: fix

#240 Fix/#239 safari fullscreen
  client/src/components/common/FullScreenMode.tsx
Labels: fix, 🐞 bug report

#232 fix: update bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: chore
