Repository woowacourse-teams/2020-zeze, pull requests merged in 2020-07, with the labels that each got.

#24 Chore/#23 coding convention
  .editorconfig
  .zeze-checkstyle.xml
  .zeze-java-convention.xml
  README.md
  build.gradle
  client/package.json
  client/src/App.test.tsx
  client/src/App.tsx
  client/src/index.tsx
  client/src/react-app-env.d.ts
  client/src/serviceWorker.ts
  client/src/setupTests.ts
  client/yarn.lock
  src/main/resources/application.yml
Labels: chore

#26 Dependencies/#25 react project initial setup
  .editorconfig
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/src/App.css
  client/src/App.tsx
  client/src/api/index.ts
  client/src/api/todo.ts
  client/src/components/archive/css/index.ts
  client/src/components/archive/index.tsx
  client/src/components/common/Footer.tsx
  client/src/components/common/Header.tsx
  client/src/components/common/Layout.tsx
  client/src/components/editor/index.tsx
  client/src/components/home/index.tsx
  client/src/components/me/index.tsx
  client/src/domains/constants.ts
  client/src/hooks/index.ts
  client/src/logo.svg
  client/src/utils/index.ts
  client/yarn.lock
Labels: chore, dependencies

#28 Build/#27 react build gradle task
  build.gradle
Labels: build

#33 Fix/#32 react router as default router
  client/src/App.tsx
  client/src/components/common/Spinner.tsx
  client/src/components/error/index.tsx
  src/main/java/dev/minguinho/zeze/controller/PageController.java
Labels: fix

#36 Build/#29 delete static script
  .gitignore
  build.gradle
Labels: build, chore

#37 Docs/#30 update code convention guide on README.md
  README.md
Labels: docs

#42 Feat/#41 Create common object and structuring user domain
  src/main/java/dev/minguinho/zeze/domain/auth/api/AuthController.java
  src/main/java/dev/minguinho/zeze/domain/auth/exception/empty.txt
  src/main/java/dev/minguinho/zeze/domain/auth/model/User.java
  src/main/java/dev/minguinho/zeze/domain/auth/service/AuthService.java
  src/main/java/dev/minguinho/zeze/domain/common/BaseEntity.java
  src/main/java/dev/minguinho/zeze/exception/ExceptionController.java
  src/main/java/dev/minguinho/zeze/exception/dto/ApiError.java
  src/main/java/dev/minguinho/zeze/pagecontroller/PageController.java
Labels: feat

#45 Feat/#8 preview
  client/package.json
  client/src/components/editor/EditMode.tsx
  client/src/components/editor/Preview.tsx
  client/src/components/editor/index.tsx
  client/yarn.lock
Labels: feat

#35 Feat/#13 presentation mode
  client/package.json
  client/public/.DS_Store
  client/src/components/common/FullScreenMode.tsx
  client/src/components/home/index.tsx
  client/src/domains/constants.ts
  client/src/index.css
  client/src/utils/fixtures.ts
  client/yarn.lock
Labels: feat

#50 Feat/#11 embed youtube
  client/src/components/editor/EditMode.tsx
  client/src/components/editor/Preview.tsx
  client/src/utils/markdown/fixtures.ts
  client/src/utils/markdown/renderer.ts
  client/src/utils/markdown/replacers/youtube.ts
Labels: feat

#48 Chore/#47 update issue template
  .github/ISSUE_TEMPLATE/-----------.md
Labels: chore

#38 Feat/#10 upload file
  .gitignore
  build.gradle
  src/main/java/dev/minguinho/zeze/domain/auth/exception/empty.txt
  src/main/java/dev/minguinho/zeze/domain/auth/model/User.java
  src/main/java/dev/minguinho/zeze/domain/common/model/BaseEntity.java
  src/main/java/dev/minguinho/zeze/domain/file/api/FileController.java
  src/main/java/dev/minguinho/zeze/domain/file/api/dto/FileUrlResponses.java
  src/main/java/dev/minguinho/zeze/domain/file/config/AwsS3Config.java
  src/main/java/dev/minguinho/zeze/domain/file/exception/FileNotConvertedException.java
  src/main/java/dev/minguinho/zeze/domain/file/model/S3Uploader.java
  src/main/java/dev/minguinho/zeze/domain/file/service/FileService.java
  src/main/java/dev/minguinho/zeze/exception/ExceptionController.java
  src/main/resources/application.yml
  src/test/java/dev/minguinho/zeze/domain/file/api/FileControllerTest.java
  src/test/java/dev/minguinho/zeze/domain/file/model/S3UploaderTest.java
  src/test/java/dev/minguinho/zeze/domain/file/service/FileServiceTest.java
  src/test/resources/http/upload_file.http
  src/test/resources/test-image.png
Labels: feat

#60 Feat/#31 markdown editor
  client/package-lock.json
  client/package.json
  client/src/components/common/editor/index.tsx
  client/src/components/editor/EditMode.tsx
  client/yarn.lock
Labels: feat

#58 Fix/#52 markdown rerendering
  client/package.json
  client/src/components/common/markdown/extensions/Youtube.tsx
  client/src/components/common/markdown/extensions/index.ts
  client/src/components/common/markdown/index.tsx
  client/src/components/common/markdown/renderers/Code.tsx
  client/src/components/common/markdown/renderers/index.ts
  client/src/components/editor/Preview.tsx
  client/src/utils/markdown/renderer.ts
  client/yarn.lock
Labels: dependencies, fix

#64 Feat/#1 oauth2 social sign in
  .gitignore
  build.gradle
  src/main/java/dev/minguinho/zeze/domain/auth/api/AuthController.java
  src/main/java/dev/minguinho/zeze/domain/auth/api/dto/request/GithubSignInDto.java
  src/main/java/dev/minguinho/zeze/domain/auth/api/dto/request/SocialAccessTokenRequestDto.java
  src/main/java/dev/minguinho/zeze/domain/auth/api/dto/response/AuthenticationDto.java
  src/main/java/dev/minguinho/zeze/domain/auth/api/dto/response/UserResourceResponse.java
  src/main/java/dev/minguinho/zeze/domain/auth/exception/empty.txt
  src/main/java/dev/minguinho/zeze/domain/auth/infra/JwtTokenProvider.java
  src/main/java/dev/minguinho/zeze/domain/auth/model/Social.java
  src/main/java/dev/minguinho/zeze/domain/auth/model/User.java
  src/main/java/dev/minguinho/zeze/domain/auth/model/UserRepository.java
  src/main/java/dev/minguinho/zeze/domain/auth/service/AuthService.java
  src/main/java/dev/minguinho/zeze/domain/auth/service/TokenService.java
  src/main/java/dev/minguinho/zeze/domain/auth/service/UserService.java
  src/main/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/accesstokenfetcher/GithubAccessTokenFetcher.java
  src/main/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/accesstokenfetcher/SocialAccessTokenFetcher.java
  src/main/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/accesstokenfetcher/SocialAccessTokenFetcherImpl.java
  src/main/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/accesstokenfetcher/dto/request/GithubAccessTokenRequestDto.java
  src/main/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/accesstokenfetcher/dto/response/GithubAccessTokenResponseDto.java
  src/main/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/accesstokenfetcher/dto/response/SocialAccessTokenResponse.java
  src/main/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/resourcefetcher/GithubResourceFetcher.java
  src/main/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/resourcefetcher/SocialResourceFetcher.java
  src/main/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/resourcefetcher/SocialResourceFetcherImpl.java
  src/main/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/resourcefetcher/dto/request/GithubResourceRequestDto.java
  src/main/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/resourcefetcher/dto/request/SocialResourceRequestDto.java
  src/main/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/resourcefetcher/dto/response/GithubResourceResponseDto.java
  src/main/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/resourcefetcher/dto/response/SocialResourceResponse.java
  src/main/java/dev/minguinho/zeze/domain/user/model/UserResource.java
  src/main/java/dev/minguinho/zeze/domain/user/model/UserResourceRepository.java
  src/main/resources/application.yml
  src/test/java/dev/minguinho/zeze/domain/auth/api/dto/request/GithubSignInDtoTest.java
  src/test/java/dev/minguinho/zeze/domain/auth/api/dto/response/UserResourceResponseTest.java
  src/test/java/dev/minguinho/zeze/domain/auth/model/SocialTest.java
  src/test/java/dev/minguinho/zeze/domain/auth/model/UserTest.java
  src/test/java/dev/minguinho/zeze/domain/auth/service/AuthServiceTest.java
  src/test/java/dev/minguinho/zeze/domain/auth/service/TokenServiceTest.java
  src/test/java/dev/minguinho/zeze/domain/auth/service/UserServiceTest.java
  src/test/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/GithubResourceFetcherTest.java
  src/test/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/accesstokenfetcher/GithubAccessTokenFetcherTest.java
  src/test/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/accesstokenfetcher/SocialAccessTokenFetcherImplTest.java
  src/test/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/resourcefetcher/SocialResourceFetcherImplTest.java
  src/test/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/resourcefetcher/dto/request/GithubResourceRequestDtoTest.java
  src/test/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/resourcefetcher/dto/response/GithubResourceResponseDtoTest.java
Labels: feat, high priority

#53 Style/#49 design publishing
  client/src/App.test.tsx
  client/src/App.tsx
  client/src/api/todo.ts
  client/src/components/archive/css/index.ts
  client/src/components/archive/index.tsx
  client/src/components/common/Card.tsx
  client/src/components/common/Cards.tsx
  client/src/components/common/Footer.tsx
  client/src/components/common/FullScreenMode.tsx
  client/src/components/common/Header.tsx
  client/src/components/common/Layout.tsx
  client/src/components/common/SidebarHeader.tsx
  client/src/components/common/SidebarLayout.tsx
  client/src/components/common/SidebarMenu.tsx
  client/src/components/common/Spinner.tsx
  client/src/components/common/Toast.tsx
  client/src/components/common/assets/archive.svg
  client/src/components/common/assets/index.ts
  client/src/components/common/assets/logo.svg
  client/src/components/common/assets/menu.svg
  client/src/components/common/assets/more.svg
  client/src/components/common/assets/newSlides.svg
  client/src/components/common/assets/play.svg
  client/src/components/common/assets/recent.svg
  client/src/components/common/assets/slide.svg
  client/src/components/common/assets/user.svg
  client/src/components/common/editor/index.tsx
  client/src/components/common/markdown/extensions/Youtube.tsx
  client/src/components/common/markdown/extensions/index.ts
  client/src/components/common/markdown/index.tsx
  client/src/components/common/markdown/renderers/Code.tsx
  client/src/components/common/markdown/renderers/Image.tsx
  client/src/components/common/markdown/renderers/index.ts
  client/src/components/common/theme/index.ts
  client/src/components/editor/EditMode.tsx
  client/src/components/editor/Preview.tsx
  client/src/components/editor/assets/index.ts
  client/src/components/editor/index.tsx
  client/src/components/home/assets/index.ts
  client/src/components/home/assets/markdown.png
  client/src/components/home/index.tsx
  client/src/components/me/index.tsx
  client/src/domains/constants.ts
  client/src/domains/types.ts
  client/src/index.css
  client/src/index.tsx
  client/src/react-app-env.d.ts
  client/src/serviceWorker.ts
  client/src/utils/fixtures.ts
  client/src/utils/markdown/fixtures.ts
Labels: style

#71 fix: modify checkstyle and code-formatter to match
  .zeze-checkstyle.xml
  .zeze-java-convention.xml
  src/main/java/dev/minguinho/zeze/domain/auth/api/AuthController.java
  src/main/java/dev/minguinho/zeze/domain/auth/api/dto/request/GithubSignInDto.java
  src/main/java/dev/minguinho/zeze/domain/auth/api/dto/request/SocialAccessTokenRequestDto.java
  src/main/java/dev/minguinho/zeze/domain/auth/model/User.java
  src/main/java/dev/minguinho/zeze/domain/auth/service/AuthService.java
  src/main/java/dev/minguinho/zeze/domain/auth/service/TokenService.java
  src/main/java/dev/minguinho/zeze/domain/auth/service/UserService.java
  src/main/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/accesstokenfetcher/GithubAccessTokenFetcher.java
  src/main/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/accesstokenfetcher/SocialAccessTokenFetcher.java
  src/main/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/accesstokenfetcher/SocialAccessTokenFetcherImpl.java
  src/main/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/accesstokenfetcher/dto/request/GithubAccessTokenRequestDto.java
  src/main/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/accesstokenfetcher/dto/response/GithubAccessTokenResponseDto.java
  src/main/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/resourcefetcher/GithubResourceFetcher.java
  src/main/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/resourcefetcher/SocialResourceFetcher.java
  src/main/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/resourcefetcher/SocialResourceFetcherImpl.java
  src/main/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/resourcefetcher/dto/request/GithubResourceRequestDto.java
  src/main/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/resourcefetcher/dto/request/SocialResourceRequestDto.java
  src/main/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/resourcefetcher/dto/response/GithubResourceResponseDto.java
  src/main/java/dev/minguinho/zeze/domain/file/api/FileController.java
  src/main/java/dev/minguinho/zeze/domain/file/model/S3Uploader.java
  src/main/java/dev/minguinho/zeze/domain/file/service/FileService.java
  src/main/java/dev/minguinho/zeze/domain/user/model/UserResource.java
  src/main/java/dev/minguinho/zeze/exception/ExceptionController.java
  src/test/java/dev/minguinho/zeze/domain/auth/service/AuthServiceTest.java
  src/test/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/GithubResourceFetcherTest.java
  src/test/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/accesstokenfetcher/GithubAccessTokenFetcherTest.java
  src/test/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/accesstokenfetcher/SocialAccessTokenFetcherImplTest.java
  src/test/java/dev/minguinho/zeze/domain/auth/service/socialfetcher/resourcefetcher/SocialResourceFetcherImplTest.java
  src/test/java/dev/minguinho/zeze/domain/file/model/S3UploaderTest.java
Labels: chore

#67 Feat/#7 crud slide
  .gitignore
  client/public/.DS_Store
  src/main/java/dev/minguinho/zeze/domain/slide/api/SlideController.java
  src/main/java/dev/minguinho/zeze/domain/slide/api/dto/SlideRequestDto.java
  src/main/java/dev/minguinho/zeze/domain/slide/api/dto/SlideResponseDto.java
  src/main/java/dev/minguinho/zeze/domain/slide/api/dto/SlideResponseDtos.java
  src/main/java/dev/minguinho/zeze/domain/slide/api/dto/SlidesRequestDto.java
  src/main/java/dev/minguinho/zeze/domain/slide/exception/SlideNotFoundException.java
  src/main/java/dev/minguinho/zeze/domain/slide/model/Slide.java
  src/main/java/dev/minguinho/zeze/domain/slide/model/SlideRepository.java
  src/main/java/dev/minguinho/zeze/domain/slide/service/SlideService.java
  src/main/resources/application.yml
  src/test/java/dev/minguinho/zeze/domain/slide/acceptance/SlideAcceptanceTest.java
  src/test/java/dev/minguinho/zeze/domain/slide/api/SlideControllerTest.java
  src/test/java/dev/minguinho/zeze/domain/slide/model/SlideRepositoryTest.java
  src/test/java/dev/minguinho/zeze/domain/slide/service/SlideServiceTest.java
Labels: feat

#56 Feat/#51 develop slide api
  client/public/.DS_Store
  client/src/api/index.ts
  client/src/api/slide.ts
  client/src/api/todo.ts
Labels: feat

#72 Feat/#68 parse metadata
  client/public/index.html
  client/src/components/archive/index.tsx
  client/src/components/common/Card.tsx
  client/src/components/common/SidebarLayout.tsx
  client/src/components/common/editor/index.tsx
  client/src/components/common/markdown/extensions/Metadata.tsx
  client/src/components/common/markdown/extensions/index.ts
  client/src/components/common/markdown/index.tsx
  client/src/components/common/markdown/renderers/Code.tsx
  client/src/components/common/theme/index.ts
  client/src/components/editor/EditMode.tsx
  client/src/components/me/index.tsx
  client/src/utils/markdown/metadata.ts
Labels: feat

#75 Chore/#74 Add open graph tags
  client/public/index.html
  client/public/og.jpeg
Labels: chore

#78 Feat/#73 highlight codeblock
  client/package.json
  client/src/components/common/markdown/renderers/Code.tsx
  client/yarn.lock
Labels: dependencies, feat

#80 Feat/#79 check style
  build.gradle
  src/main/java/dev/minguinho/zeze/domain/slide/api/SlideController.java
  src/main/java/dev/minguinho/zeze/domain/slide/api/dto/SlideRequestDto.java
  src/main/java/dev/minguinho/zeze/domain/slide/api/dto/SlideResponseDto.java
  src/main/java/dev/minguinho/zeze/domain/slide/api/dto/SlideResponseDtos.java
  src/main/java/dev/minguinho/zeze/domain/slide/model/Slide.java
  src/main/java/dev/minguinho/zeze/domain/slide/service/SlideService.java
  src/test/java/dev/minguinho/zeze/domain/slide/acceptance/SlideAcceptanceTest.java
  src/test/java/dev/minguinho/zeze/domain/slide/api/SlideControllerTest.java
Labels: fix

#83 Fix/#76 hide mouse pointer
  client/src/components/common/assets/index.ts
  client/src/components/common/theme/index.ts
Labels: fix

#85 ci: add github action deploy workflow yml
  .github/workflows/deploy.yml
Labels: ci

#86 Ci/#34 deploy automation & pr integration
  .github/workflows/build.yml
  .github/workflows/deploy.yml
Labels: ci
